### ISSUE TITLE
Video call error

### ISSUE THREAD

**Issue by sonshark** [HyphenateInc/IMDemo_android#91]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hyphenate.chatuidemo.call.VideoCallActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class com.hyphenate.media.EMOppositeSurfaceView

Didn't find class "com.hyphenate.media.EMOppositeSurfaceView"

**Comment by githubzhaoliang** [comment]
EMOppositeSurfaceView and EMLocalSurfaceView has combined to one EMCallSurfaceView.

Please update your code from our repo.
And you can check release note for your reference: https://docs.hyphenate.io/docs/android-sdk-release-notes

**Comment by sonshark** [comment]
Thanks you!

I changed to EMCallSurfaceView. App work well!
